#!/bin/bash
# configure ruby 1.6.8 build for arm-linux -- 8/17/09 brent@mbari.org
# for gcc x86 add:
# -mpreferred-stack-boundary=2 -fno-stack-protector
# for gcc x86 4.x add:
# -fno-inline-functions-called-once
# to CFLAGS
: ${CFLAGS:="-O2 -g"}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${ARMPREFIX:=$ARMGCC/usr}
: ${CC:=$ARMGCC/bin/gcc}
: ${TARGETTOP:=${1-/usr/local}}
export CC CFLAGS CXXFLAGS
cd ${RUBYVERS-ruby-1.6.8-mbari}
[ -r Makefile ] && make distclean
tarargs=" 1 --keep-old-files -xzf ../snapshot-1.6.tar.gz"
tar --strip-path $tarargs 2>tarerrs
result=$?  #cope with new and old gnu tar versions
[ $result = 64 ] && {
  tar --strip-components $tarargs 2>tarerrs
  result=$?
}
[ $result != 0 -a $result != 2 ] && {  #we expect File exists errors
  cat tarerrs >&2
  exit $result
}
rm -rf disabled_ext &&
mkdir -p disabled_ext &&
mv ext/tk ext/tcltklib ext/curses disabled_ext &&
rm -f config.cache configure && autoconf &&
ac_cv_func_memcmp_working=yes \
ac_cv_func_getpgrp_void=yes ac_cv_func_setpgrp_void=yes \
configure --host=arm-unknown-linux $@ || exit 2
echo 'Patching RUBY_*_LIB* in config.h for target'
sed -e "s:\"$ARMPREFIX:\"$TARGETTOP:g" config.h >config.h.patched || {
  echo "Failed to patch config.h"
  exit 3
}
#collect the trash more often
echo "#define GC_MALLOC_LIMIT 2000000" >> config.h.patched 
mv -f config.h.patched config.h || exit 6

  echo "  $ arminstall       #to install ruby and core libaries"
