#!/bin/sh
# install ruby 1.6.8 build for arm-linux -- 11/25/05 brent@mbari.org
# also install modules needed for ESP unless 
#   coreOnly environment variable is set
#
# $1 = top directory of installation on the target [/usr/local]
# $2 = top directory on the host [$HOME/$1]
# $3 = temporary install directory [/tmp]
# 
# remove all fields $1 from list delminited by $2 starting with $3
# send the filtered version of $2 to stdout
remove ()
{
  toDelete=$1
  IFS=$2
  shift 2
  [ "$@" ] && {
    set $@
    unset separator
    for field; do
      if [ "$field" != "$toDelete" ]; then
        echo -n "$separator$field"
        separator=$IFS
      fi
    done
  }
}

startDir=$PWD
export DESTDIR=${3:-$HOME/armHost}
: ${ARMGCC:=/arm}
: ${ARMPREFIX:=$ARMGCC/usr}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${TARGETTOP:=${1-/usr/local}}
: ${HOSTTOP:=${2-$DESTDIR$TARGETTOP}}

echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
PATH=`remove . : $PATH`  #remove current directory from PATH
cd ${RUBYVERS:=ruby-1.6.8-mbari} || exit 98
top=$PWD
if [ ! -x miniruby ]; then
  echo Building miniruby for this machine
  rm -f *.o && make CC=gcc miniruby || {
    echo "could not build miniruby"
    exit 8
  }
  rm *.o
  echo Building ruby for ARM target
fi
export RUBYLIB=$PWD
rbcfg=rbconfig.rb
make -o miniruby fake.rb $rbcfg

#This is required so that ruby's extmk.rb script will look in the target
#libs when checking dependencies.
export prefix=$ARMPREFIX

rm -rf $HOSTTOP/bin/ruby $HOSTTOP/lib/ruby &&
mkdir -p $HOSTTOP &&
make -o miniruby all install || exit 1
[ -n "$coreOnly" ] || {
  echo "   Installing extensions required by MBARI ESP:"
  cd $startDir
  PATH=.:$PATH
  buildUtils clean install || exit 9
}

if false; then
  echo Patching prefix in ext/extmk.rb for target
  cd $top/ext &&
  sed -e "s:prefix = $ARMPREFIX:prefix = $TARGETTOP:" extmk.rb \
    >extmk.rb.patched && mv -f extmk.rb.patched extmk.rb || {
    echo "Failed to patch extmk.rb"
    exit 3
  }
fi

echo "Changing prefix from $ARMGCC to $TARGETTOP in $rbcfg"
cd $top &&
sed -e "s:+ \"$prefix\":+ \"$TARGETTOP\":" $rbcfg >$rbcfg.patched &&
mv -f $rbcfg.patched $rbcfg || {
  echo "Failed to patch $rbcfg"
  exit 2
}

cd $HOSTTOP || exit 2

echo "Stripping, Deleting docs, intermediate files and empty directories"
rm -rf `find -name man`
rm -f `find lib/ruby -name "*.[aoh]"` #remove all development intermediate files
find lib/ruby/1.6 -depth -type d \
  -exec rmdir {} --ignore-fail-on-non-empty \;
objs="bin/ruby `find lib/ruby -name "*.so*"`"
chmod +w $objs &&
$ARMSTRIP $objs &&
chmod -w $objs || exit 8
echo "Successfully Installed Ruby environment at $HOSTTOP"


