#!/bin/bash
#Build and optionally install the extra ruby utilities MBARI needs for ESP
#parameters are passed on to make
#to force complete rebuild:  buildUtils clean all
#to install for an arm host, force our ruby to load a different rbconfig.rb:
# RUBYLIB=~/armHost/usr/local/lib/ruby/1.6/arm-linux buildUtils clean install

toolDirs='mbarilib termios'
top=$PWD
ruby=`which ruby 2>/dev/null` || ruby=../ruby-1.6.8/miniruby
for d in $toolDirs; do
  echo "Making $d:"
  cd $d
  $ruby extconf.rb || exit 1
  make $@ || exit 1
  cd ..
done

for mktarget; do  #for things that don't have an explicit "build" operation
  [ "$mktarget" = "install" ] && {  #install IRB and MBARI misc extensions
    echo "Installing IRB and MBARI extensions..."
    (cd irb-0.9-02.09.03; ./instirb.rb $DESTDIR)
    (cd irbtools-0.9; ./inst-irbtools.rb $DESTDIR)
    ./inst-mbari.rb $DESTDIR || exit 32
    break
  }
done
