#!/bin/bash
#Build the extra ruby utilities MBARI needs for ESP
#first parameter is typically "clean" or omitted
toolDirs='mbarilib termios'
[ -n "$1" ] && target=$1
top=$PWD
ruby=$2
[ -z "$ruby" ] && {
  ruby=`which ruby 2>/dev/null`
  [ "$?" = 0 -a -x $ruby ] || ruby=../ruby-1.6.8/miniruby
}
for d in $toolDirs; do
  echo "Making $d:"
  cd $d
  $ruby extconf.rb || exit 1
  make $target all || exit 1
  cd ..
done

ruby=$PWD
cd $HOME
[ -f .irbrc ] && mv .irbrc .irbrc.save
cp $top/irbrc .irbrc
