#!/bin/bash
#Build ruby
cd ${RUBYVERS:=ruby-1.6.8}
[ -n "$1" ] && target=$1
echo "Making $target in $RUBYVERS:"
make $target
if [ ! -r Makefile ]; then
  CFLAGS=-O2 CXXFLAGS=-O2 configure
fi
echo "Making $RUBYVERS:"
make
