#!/bin/bash
#Install ruby and core utilities
#to install for an arm host, force our ruby to load a different rbconfig.rb:
#  RUBYLIB=~/armHost/usr/local/lib/ruby/1.6/arm-linux installUtils

toolDirs='mbarilib termios'
prefix=$1  #optional installation prefix
shift  #pass extra options on to make

echo "Installing ruby utilities:  $toolDirs"

for d in $toolDirs; do
  echo "Installing $d:"
  (cd $d; make install $@)
done

echo "Installing IRB and MBARI extensions..."
(cd irb-0.9-02.09.03; ./instirb.rb $prefix)
(cd irbtools-0.9; ./inst-irbtools.rb $prefix)
./inst-mbari.rb $prefix
