#!/bin/bash
# unpack & configure libtiff build for arm-linux -- 2/25/25 brent@mbari.org
: ${CFLAGS:=-Os -fomit-frame-pointer}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${TIFFVERS:=tiff-3.9.4}
export CFLAGS CXXFLAGS GCOPTS=$CFLAGS
top=$PWD
rm -rf $TIFFVERS && tar zxf ${TIFFVERS}[-.]tar.gz 2>/dev/null || exit $?
if [ $TIFFVERS == v3.4 ]; then
  cp -f armport.h $TIFFVERS/libtiff/port.h &&
  cd $TIFFVERS &&
  patch -p1 <$top/tiff-v3.4.patch
  ARMTOP=$ARMGCC configure --host=$ARMHOST --noninteractive
else
  cd $TIFFVERS
  configure --host=$ARMHOST --disable-cxx --disable-jpeg
fi && echo "Now, run arminstall"
