#!/bin/sh
# build & install libtiff for arm-linux -- 2/25/25 brent@mbari.org

: ${TIFFLIBV:=3.9.4}
: ${TIFFVERS:=tiff-$TIFFLIBV}
: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${HOSTTOP:=${1-$HOME/armHost}}

cplinks() {
#recursively copy symlinks having the specified target $1
  for target in `find -lname "$1"`; do
    cp -a $target $2 || return $?
    cplinks $target $2
  done
}

cplib() {
#copy and strip ARM library $1 and all symlinks to it
   $ARMSTRIP $1 -o $2/$1 && cplinks $*
}

echo "Installing in $HOSTTOP"
cd $TIFFVERS || exit 2
make || exit 1

#set -x
cd libtiff &&
  cp -f tiffconf.h tiff.h tiffio.h tiffvers.h $ARMPREFIX/include &&
cd .libs || exit $?

lib=libtiff.so.$TIFFLIBV
cp $lib $ARMPREFIX/lib/$lib && cplinks $lib $ARMPREFIX/lib &&
cplib $lib $HOSTTOP/usr/lib && cd ../../tools/.libs || exit $?
for tool in tiffcp tiffinfo tiffdump; do
  $ARMSTRIP $tool -o $HOSTTOP/usr/bin/$tool
done
echo "Done."
