#!/bin/sh
# unpack and patch wget for arm-linux -- 3/18/16 brent@mbari.org

: ${CFLAGS:="-Os -fomit-frame-pointer"}
: ${CXXFLAGS:=$CFLAGS}
: ${ARMGCC:=/arm}
: ${CC:=$ARMGCC/bin/gcc}
: ${LIBTOP:=${1-$ARMGCC}}
: ${TIMELIMITVERS:=timelimit-1.8}
export CC CFLAGS
rm -rf $TIMELIMITVERS && tar xzf $TIMELIMITVERS.tar.gz && cd $TIMELIMITVERS &&
echo "Next, run arminstall here, or just make and install on target"
