=begin

  rbbr/config.rb

    This file is automatically generated by rbbr installer.

=end

module RBBR
  module Config
    DATA_DIR = '/usr/local/share/rbbr'
    ICONV_SRC_CHARSET = 'EUC-JP'
  end
end
