#!/bin/sh
# build & install libreadline-4.3 for arm-linux -- 2/18/05 brent@mbari.org

: ${ARMGCC:=/arm}
: ${ARMSTRIP:=$ARMGCC/bin/strip}
: ${LIBTOP:=$ARMGCC/usr}
: ${TARGETTOP:=${2-/usr/lib}}
: ${HOSTTOP:=${1-$HOME/armHost$TARGETTOP}}
echo "Installing in $HOSTTOP"
echo "  for execution at $TARGETTOP on the ARM target"
cd ${READLNVERS-readline-4.3} || exit 2
make install || exit 1
mkdir -p $HOSTTOP || exit 3
for lib in libreadline libhistory; do
  cp -af $LIBTOP/lib/$lib.so*[^.old] $HOSTTOP &&
  $ARMSTRIP $HOSTTOP/$lib.so.?.? || exit 3
done
echo "Done."
