#!/bin/sh
# install ruby 1.6.8 build for arm-linux -- 2/24/03 brent@mbari.org
export DESTDIR=${1:-`pwd`/arm}  #where to store ruby installation on the host
[ -d $DESTDIR ] && rm -rf $DESTDIR
make install #to $DESTDIR
cd $DESTDIR || exit
rm -rf `find -name man`
rm -f `find -name "*.[aoh]"` #remove all compiler & linker intermediate files
arm-linux-strip `find -name "*.so"`
arm-linux-strip `find -name bin`/ruby
